ARG RUBY_VERSION=3.4.0-rc1
FROM docker.io/library/ruby:$RUBY_VERSION-slim AS base
ENV RAILS_ENV=development

COPY package.json /rails/package.json
COPY yarn.lock /rails/yarn.lock

# Rails app lives here
WORKDIR /rails
# Install base packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl build-essential libpq-dev libjemalloc2 libvips postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives
# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle lock --add-platform ruby
RUN bundle lock --add-platform x86_64-linux
RUN gem install mini_portile2 -v 2.8.0
RUN bundle install -j $(nproc)
# Copy application code
COPY . .

# Install Node.js and npm
RUN apt-get update \
    && apt-get install -y curl \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g yarn \
    && rm -rf /var/lib/apt/lists/*
